create table news
(
    id    bigint generated by default as identity,
    time  timestamp(0) default current_timestamp(0),
    text  text not null,
    title varchar(255) not null,
    user_id bigint not null,
    primary key (id)
);